// Fixtures de rendu pour le harness E2E des blocs shared (B11). Déterministes, sans média
// distant instable (images = asset local /icon.png ou data:image ; embeds = providers réels
// pour vérifier l'URL canonique, pas leur chargement). Base = defaultContent du bloc, surchargé
// par FILL pour peupler les répéteurs/médias qui rendraient sinon un état vide.
const IMG = "/icon.png" // asset local same-origin, déterministe

export const FILL: Record<string, Record<string, any>> = {
  // ── Vague LAYOUT — 35 blocs « Création libre » ──
  free_section: { eyebrow: "NOTRE MAISON", title: "Une cuisine de saison", subtitle: "Carte renouvelée chaque mois", text: "Produits frais, fournisseurs locaux, tout est préparé sur place.", cta_label: "Réserver", cta_url: "https://exemple.com", cta2_label: "Voir la carte", cta2_url: "https://exemple.com", bg_type: "Carte" },
  image_text: { image: IMG, title: "Notre savoir-faire", text: "Trente ans de métier, transmis de père en fille.", cta_label: "En savoir plus", cta_url: "https://exemple.com", side: "Gauche" },
  split_panel: { l_emoji: "🍽️", l_title: "Sur place", l_text: "Service de 12h à 14h", l_cta_label: "Réserver", l_cta_url: "https://exemple.com", r_emoji: "🥡", r_title: "À emporter", r_text: "Prêt en 15 minutes", r_cta_label: "Commander", r_cta_url: "https://exemple.com" },
  overlay_card: { image: IMG, eyebrow: "LA MAISON", title: "Bienvenue chez nous", subtitle: "Ouvert du mardi au samedi", cta_label: "Réserver une table", cta_url: "https://exemple.com" },
  frame_box: { emoji: "✨", title: "Le mot du chef", text: "Chaque assiette est pensée comme une saison entière.", signature: "— Marie, cheffe de cuisine" },
  banner_strip: { emoji: "🚚", text: "Livraison offerte dès 25 €", cta_label: "J'en profite", cta_url: "https://exemple.com" },
  full_bleed_image: { image: IMG, caption: "Notre salle, un soir de service", height: "Moyenne" },
  stack_cards: { title: "Nos formules", c1_image: IMG, c1_badge: "Populaire", c1_title: "Formule midi", c1_text: "Entrée + plat + café — 18 €", c1_label: "Voir", c1_url: "https://exemple.com", c2_title: "Menu du soir", c2_text: "Trois services — 34 €", c3_title: "Brunch du dimanche", c3_text: "À volonté — 26 €" },
  free_grid: { title: "Nos spécialités", columns: "2", c1_emoji: "🥐", c1_title: "Viennoiseries", c1_text: "Faites maison chaque matin", c2_emoji: "🍞", c2_title: "Pains au levain", c2_text: "Fermentation 24 h", c3_emoji: "🎂", c3_title: "Pâtisseries", c3_text: "Sur commande", c4_emoji: "☕", c4_title: "Café de spécialité", c4_text: "Torréfié à Reims" },
  columns_text: { title: "Infos pratiques", columns: "2", c1_emoji: "🕐", c1_title: "Horaires", c1_text: "Mar–Sam\n12h–14h · 19h–22h", c2_emoji: "📍", c2_title: "Adresse", c2_text: "12 rue des Halles\n51100 Reims" },
  image_mosaic: { title: "En images", img1: IMG, img2: IMG, img3: IMG, img4: IMG, img5: IMG, caption: "Quelques instants du service" },
  logo_marquee: { title: "Ils nous font confiance", logo1: IMG, logo2: IMG, name3: "Maison Durand", logo4: IMG, name5: "Ferme du Pré" },
  avatar_row: { img1: IMG, name1: "Marie", img2: IMG, name2: "Paul", name3: "Sofia", count: "+400", label: "Ils nous ont fait confiance", sublabel: "Depuis l'ouverture" },
  shape_divider: { shape: "Vague", height: "56" },
  decor_line: { center: "✦", line_style: "Dégradé" },
  marquee_text: { items: "Ouvert 7j/7, Terrasse chauffée, Wi-Fi gratuit", separator: "✦" },
  ribbon_banner: { emoji: "🎉", text: "Nouveau" },
  color_band: { fill: "Dégradé", height: "48" },
  big_statement: { text: "Le goût du vrai.", subtext: "Depuis 1998, rue des Halles", size: "Très grande", fill: "Dégradé" },
  text_columns: { title: "Notre histoire", text: "La maison a ouvert en 1998 dans une ancienne mercerie. Trois générations y ont travaillé, et la recette du pain n'a jamais changé. Aujourd'hui encore, le levain est nourri chaque matin avant l'ouverture.", columns: "2", dropcap: "Oui" },
  numbered_list: { title: "Nos 3 engagements", i1_title: "Produits frais", i1_text: "Livrés chaque matin par nos producteurs", i2_title: "Zéro gaspillage", i2_text: "Les invendus partent à l'association du quartier", i3_title: "Prix justes", i3_text: "La même carte midi et soir" },
  checklist: { title: "Compris dans la formule", i1: "Entrée + plat + dessert", i2: "Café ou thé", i3: "Boissons alcoolisées", i3_state: "Exclu", i4: "Pain à volonté" },
  definition_list: { title: "En pratique", r1_label: "Durée", r1_value: "45 minutes", r2_label: "Sur rendez-vous", r2_value: "Oui", r3_label: "Tarif", r3_value: "38 €", r3_strong: "Oui" },
  card_link: { image: IMG, eyebrow: "LA CARTE", title: "Voir le menu du soir", text: "Mis à jour chaque semaine", url: "https://exemple.com" },
  anchor_nav: { i1_label: "La carte", i1_emoji: "🍽️", i1_target: "carte", i2_label: "Horaires", i2_emoji: "🕐", i2_target: "horaires", i3_label: "Nous trouver", i3_emoji: "📍", i3_target: "acces" },
  anchor_target: { name: "carte" },
  toggle_content: { title: "Conditions", text: "Les réservations sont conservées quinze minutes après l'heure convenue. Au-delà, la table peut être réattribuée. Pour les groupes de plus de huit personnes, un acompte est demandé à la réservation.", preview_lines: "2" },
  back_to_top: { label: "Haut de page" },
  steps_horizontal: { title: "Comment ça marche", s1_emoji: "📱", s1_title: "Scannez", s1_text: "Avec l'appareil photo", s2_emoji: "👀", s2_title: "Choisissez", s2_text: "Le créneau qui vous va", s3_emoji: "✅", s3_title: "C'est réservé", s3_text: "Confirmation immédiate" },
  stat_hero: { eyebrow: "DEPUIS 2009", value: "15", unit: "ans", label: "au service du quartier", text: "Et toujours la même équipe", fill: "Dégradé" },
  badge_row: { title: "Nos labels", items: "Fait maison, Bio, Local, Sans gluten" },
  icon_row: { title: "Sur place", i1_emoji: "📶", i1_label: "wifi", i2_emoji: "🌿", i2_label: "Terrasse", i3_emoji: "♿", i3_label: "Accès PMR", i4_emoji: "🐕", i4_label: "Animaux acceptés" },
  compare_two: { title: "Pourquoi nous choisir", left_title: "Chez nous", right_title: "Ailleurs", r1_left: "Rendez-vous en 24 h", r1_right: "Plusieurs semaines d'attente", r2_left: "Devis gratuit", r2_right: "Frais de déplacement", r3_left: "Garantie 2 ans", r3_right: "Garantie légale seule" },
  progress_bars: { title: "Où en est le projet", b1_label: "Objectif de la cagnotte", b1_value: "72", b1_note: "3 600 € / 5 000 €", b2_label: "Travaux réalisés", b2_value: "45", b3_label: "Places réservées", b3_value: "90" },
  highlight_box: { emoji: "💡", title: "Bon à savoir", text: "Le parking de la place est gratuit après 19 h." },
  // ── répéteurs / cartes (waves 1-5) ──
  testimonials: { name1: "Alice Martin", text1: "Service impeccable, je recommande.", stars1: "5", name2: "Bob Durand", text2: "Très pro.", stars2: "4" },
  business_stats: { stat1_icon: "🚀", stat1_value: "500+", stat1_label: "Clients", stat2_value: "12", stat2_label: "Ans" },
  brands: { title: "Ils nous font confiance", brand1_icon: "🍎", brand1_name: "Apple", brand2_icon: "🎧", brand2_name: "Spotify" },
  lineup: { title: "Line-up", a1_name: "DJ Snake", a1_stage: "Mainstage", a1_time: "22:00", a1_headliner: "yes", a2_name: "Petit Biscuit", a2_time: "20:00" },
  reassurance: { g1_icon: "🚚", g1_label: "Livraison rapide", g1_desc: "Sous 48h", g2_icon: "🔒", g2_label: "Paiement sûr" },
  timeline: { title: "Parcours", e1_date: "2020", e1_title: "Création", e1_desc: "Lancement", e1_link_url: "https://instagram.com/evenement", e1_link_label: "Voir l'événement", e2_date: "2023", e2_title: "Croissance" },
  menu_section: { category: "Entrées", menu_display: "Grande carte dépliable", item1_name: "Salade César", item1_price: "9€", item1_desc: "Poulet, parmesan", item2_name: "Soupe", item2_price: "6€" },
  services_list: { title: "Nos services", s1_icon: "✂️", s1_name: "Coupe", s1_desc: "30 min", s2_icon: "🎨", s2_name: "Couleur" },
  promo_banner: { emoji: "🔥", text: "Soldes -50%", subtext: "Jusqu'à dimanche", cta_label: "En profiter", cta_url: "https://exemple.com" },
  gift_card: { title: "Offrez une expérience", description: "Carte cadeau", amount1: "25€", amount2: "50€", amount3: "100€", cta_label: "Offrir", cta_url: "https://exemple.com" },
  event_info: { name: "Vernissage", date: "12 sept.", time: "18:00", location: "Galerie Nord", price: "Gratuit", cta_label: "Je viens", cta_url: "https://exemple.com" },
  event_ticketing: { event_name: "Concert live", date: "20 oct.", location: "Zénith", price: "35€", label: "Réserver", url: "https://exemple.com", platform: "Weezevent" },
  // ── média simples (wave 6) ──
  image: { src: IMG, alt: "Logo QRowg", caption: "Notre logo", ratio: "square" },
  portfolio_work: { title: "Réalisations", work1_img: IMG, work1_title: "Projet A", work1_desc: "Branding", work2_title: "Projet B", cta_label: "Tout voir", cta_url: "https://exemple.com" },
  favorite_links: { title: "Mes liens", link_1_icon: "🌐", link_1_label: "Site web", link_1_url: "https://exemple.com", link_2_icon: "📸", link_2_label: "Instagram", link_2_url: "https://exemple.com" },
  concerts: { title: "Tournée", c1_date: "12/09", c1_city: "Paris", c1_venue: "Olympia", c1_url: "https://exemple.com", c2_date: "15/09", c2_city: "Lyon" },
  merch: { title: "Boutique", img1: IMG, name1: "T-shirt", price1: "25€", img2: IMG, name2: "Casquette", price2: "18€", cta_label: "Voir tout", cta_url: "https://exemple.com" },
  app_download: { ios_url: "https://apps.apple.com/app/id1", android_url: "https://play.google.com/store/apps/details?id=x" },
  // ── média interactifs (wave 7) ──
  video_local: { src: "https://exemple.com/video.mp4", poster: IMG, title: "Ma vidéo", ratio: "16:9" },
  audio_player: { src: "https://exemple.com/audio.mp3", cover: IMG, title: "Mon titre", artist: "Artiste", show_download: "yes" },
  pdf_viewer: { title: "Brochure PDF", description: "Notre catalogue", url: "https://exemple.com/doc.pdf", pages: "12", cta_label: "Consulter" },
  spotify_embed: { url: "https://open.spotify.com/track/4cOdK2wGLETKBW3PvgPWqT", size: "md" },
  spotify_player: { title: "Ma musique", url: "https://open.spotify.com/artist/x" },
  before_after: { title: "Avant / Après", before_img: IMG, after_img: IMG, before_label: "Avant", after_label: "Après" },
  // ── débloqués (wave 8) ──
  video: { url: "https://www.youtube.com/watch?v=dQw4w9WgXcQ", title: "Vidéo démo" },
  google_maps_embed: { label: "Nous trouver", address: "10 rue de la Paix, Paris", height: "md", show_directions: "yes" },
  album_block: { title: "Mon Album", artist: "Mon Nom", cover: IMG, year: "2025", tracks: "12 titres", spotify_url: "https://open.spotify.com/album/x", apple_url: "https://music.apple.com/x" },
  discography: { title: "Discographie", a1_cover: IMG, a1_title: "Premier", a1_year: "2022", a1_type: "Album", a1_url: "https://open.spotify.com/album/x", a2_title: "Single", a2_type: "Single" },
  podcast_links: { podcast_name: "Mon Podcast", cover_url: IMG, description: "Chaque semaine", spotify_url: "https://open.spotify.com/show/x", apple_url: "https://podcasts.apple.com/x" },
  product_catalog: { title: "Catalogue", p1_img: IMG, p1_name: "Produit A", p1_price: "29€", p1_desc: "Best-seller", p1_url: "https://exemple.com", p2_name: "Produit B", p2_price: "39€", cta_label: "Acheter" },
  // ── répéteurs info/business (waves 3-4) ──
  process_steps: { title: "Comment ça marche", s1_title: "Étape 1", s1_desc: "Inscription", s2_title: "Étape 2", s2_desc: "Création" },
  on_site_services: { s1_icon: "📶", s1_label: "Wi-Fi gratuit", s2_icon: "🅿️", s2_label: "Parking" },
  engagements: { e1: "Sans engagement", e2: "Annulation gratuite", e3: "Satisfait ou remboursé" },
  trust_badge: { b1_icon: "✅", b1_label: "Certifié bio", b2_icon: "🏆", b2_label: "Élu produit de l'année" },
  stats_block: { s1_icon: "👥", s1_value: "10k", s1_label: "Abonnés", s2_icon: "⭐", s2_value: "4.9", s2_label: "Note" },
  event_program: { title: "Programme", s1_time: "09h", s1_title: "Accueil", s1_desc: "Café", s2_time: "10h", s2_title: "Conférence" },
  advantages: { title: "Avantages", adv1: "Rapide", adv2: "Fiable", adv3: "Abordable" },
  // ── CTA / atomes (waves 1-2) : defaultContent suffit généralement, on renforce ──
  whatsapp_button: { phone: "+33612345678", label: "Écrivez-nous" },
  email_button: { email: "contact@exemple.com", label: "Nous écrire" },
  download_file: { label: "Télécharger le guide", url: "https://exemple.com/guide.pdf" },
  order_online: { label: "Commander", url: "https://exemple.com" },
  donation: { label: "Soutenir", url: "https://ko-fi.com/x", platform: "Ko-fi" },
  google_review: { label: "Laisser un avis", url: "https://g.page/r/x" },
  heading: { text: "Titre de section", subtitle: "Un sous-titre" },
  bio: { text: "Créateur de contenu passionné par le web et la musique." },
  values: { title: "Nos valeurs", v1: "Qualité", v2: "Écoute", v3: "Innovation" },
  pricing: { title: "Tarifs", title1: "Starter", price1: "9€", desc1: "Pour débuter", title2: "Pro", price2: "29€", desc2: "Le plus choisi", cta_label: "Choisir", cta_url: "https://exemple.com" },
  skills: { title: "Compétences", skill1: "Design", skill2: "Développement", skill3: "SEO" },
  languages: { title: "Langues", lang1: "Français", level1: "Natif", lang2: "Anglais", level2: "Courant" },
  // Le bloc « Horaires » n'avait AUCUNE garniture : le harnais le rendait vide,
  // c'est-à-dire qu'il ne montrait ni le tableau, ni le badge, ni la bannière de
  // congés — les trois choses qu'on vient y regarder. Contenu de vrai commerçant,
  // congés d'été compris : c'est ainsi qu'on a vu la bannière et le badge se
  // contredire (cf. lib/congesDates.ts).
  opening_hours: { title: "Horaires", mode: "Simple (Lun-Ven / Sam / Dim)", mon_fri: "9h - 18h", saturday: "10h - 16h", sunday: "Fermé", exception: "Fermé du 1er au 15 août", note: "Réservation recommandée" },
}
